In [1]:
import numpy as np

In [2]:
my_list = [10,20,30,40]

In [3]:
type(my_list)

list

In [4]:
np.array(my_list)

array([10, 20, 30, 40])

In [5]:
my_numpy_array = np.array(my_list)

In [6]:
type(my_numpy_array)

numpy.ndarray

In [7]:
my_numpy_array.max

<function ndarray.max>

In [8]:
my_numpy_array.max()

np.int64(40)

In [14]:
my_list_1 = [1,2]

In [15]:
my_list_2 = [3,4]

In [17]:
my_list_1 + my_list_2

[1, 2, 3, 4]

In [18]:
my_numpy_array_1 = np.array(my_list_1)
my_numpy_array_2 = np.array(my_list_2)
my_numpy_array_1 + my_numpy_array_2

array([4, 6])

In [19]:
my_numpy_array_1 * 5

array([ 5, 10])

In [20]:
np_array = np.arange(0,10)

In [21]:
np_array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.random.randn(3,3)

array([[ 1.09022581, -0.48314849,  0.44317839],
       [-2.37208126, -0.67556266,  0.93000349],
       [ 0.91529882, -0.51477432,  1.17159249]])

In [23]:
np.random.randint(10,90,5)

array([48, 23, 89, 48, 28])